### PR TITLE
Auto-Detect patches (Normal and streamboard)

### PR DESCRIPTION
**Pull request by WXbet**
Normal patches (-p1) and streamboard-style patches (-p0) are now automatically detected and applied accordingly.
thx Schimmelreiter

### CODE REVIEW

**Comment by gorgone** [comment]
please add simple single patch example to fix the cat grep in streamboardpatch

**Comment by WXbet** [comment]
What do you mean by that?

**Comment by gorgone** [comment]
i need just one example patch to change this line this is bad code
`cat $1 | grep -e '^\(---\|+++\) ' | grep -v /dev/null | awk '{print $2}' | sort | uniq`

**Comment by WXbet** [comment]
Okay:
**p0-patch**
```
--- config.h
+++ config.h
@@ -2,11 +2,11 @@
 #define CONFIG_H_

 #define WITH_EMU 1
-//#define WITH_SOFTCAM 1
+#define WITH_SOFTCAM 1
 #define WEBIF 1
 #define WEBIF_LIVELOG 1
 #define WEBIF_JQUERY 1
```

**p1-patch**
```
--- a/config.h
+++ b/config.h
@@ -2,11 +2,11 @@
 #define CONFIG_H_

 #define WITH_EMU 1
-//#define WITH_SOFTCAM 1
+#define WITH_SOFTCAM 1
 #define WEBIF 1
 #define WEBIF_LIVELOG 1
 #define WEBIF_JQUERY 1
```

**Comment by gorgone** [comment]
this patch works without modify in s3

**Comment by WXbet** [comment]
No. Patches that require the patch -p1 instructions like the **p1 patch** example above will not work, because s3 uses patch -p0.

**Comment by gorgone** [comment]
i take a look into it

**Comment by gorgone** [comment]
check my solution
mayby i messed the trunk a bit up :-P

**Comment by WXbet** [comment]
First, p1-patches are not bad, these are the normal ones in most cases, because many tools produce this kind of patches with standard settings ;-). If I interpreted it correct, your solution changed the patch files, so that -p0 works. Am I right?

**Comment by gorgone** [comment]
Yes, and only a single line in the menu is required for it to work there.

**Comment by gorgone** [comment]
https://github.com/gorgone/createpatch/blob/master/makepatch

try this
it needs to change a bit for english translation cleanup

**Comment by WXbet** [comment]
Okay

**Comment by WXbet** [comment]
Patches, that adding files not working with your variant supporting p1-patches.

The statement
if [ ! -f "$svndir/$fil" ]
works wrong in this case and you remove the path from the patch file.

Pleae recheck the variants of Schimmelreiter above. This implementation DONT CHANGE patch files.

**Comment by gorgone** [comment]
tested 
add 2 nonexisting files

`--- oscam-svn/blabla.c<>1970-01-01 01:00:00.000000000 +0100
+++ blabla.c<-->2020-03-08 12:28:19.579089653 +0100
@@ -0,0 +1,7 @@
+#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing
--- oscam-svn/blabla.h<>1970-01-01 01:00:00.000000000 +0100
+++ blabla.h<-->2020-03-08 12:28:19.579089653 +0100
@@ -0,0 +1,7 @@
+#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing#nothing
+#nothing#nothing#nothing#nothing#nothing#nothing#nothing
`


please add non working example

**Comment by gorgone** [comment]
tested with 
./s3 native all_off USE_PATCH

**Comment by gorgone** [comment]
changed to p1

**Comment by gorgone** [comment]
i think its solved

**Pull request closed without merging**
